// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBimr1cPZYwA2WLPThXFXkHoRVPO2F_SaE',
    appId: '1:700451722816:web:32ea9ce4e0acf412e871a5',
    messagingSenderId: '700451722816',
    projectId: 'ascend-eeaae',
    authDomain: 'ascend-eeaae.firebaseapp.com',
    storageBucket: 'ascend-eeaae.firebasestorage.app',
    measurementId: 'G-BRC35CKN4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYkyjxF1oNi1Qj9OB_HQT0jP15-QZLmxA',
    appId: '1:700451722816:android:02b52c16aaf287c8e871a5',
    messagingSenderId: '700451722816',
    projectId: 'ascend-eeaae',
    storageBucket: 'ascend-eeaae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATFXJFKJx927zgIuCmBaOvEGTIcLrwOfo',
    appId: '1:700451722816:ios:8a38372195aab32be871a5',
    messagingSenderId: '700451722816',
    projectId: 'ascend-eeaae',
    storageBucket: 'ascend-eeaae.firebasestorage.app',
    iosBundleId: 'com.example.ascend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATFXJFKJx927zgIuCmBaOvEGTIcLrwOfo',
    appId: '1:700451722816:ios:8a38372195aab32be871a5',
    messagingSenderId: '700451722816',
    projectId: 'ascend-eeaae',
    storageBucket: 'ascend-eeaae.firebasestorage.app',
    iosBundleId: 'com.example.ascend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBimr1cPZYwA2WLPThXFXkHoRVPO2F_SaE',
    appId: '1:700451722816:web:679177194475c2fae871a5',
    messagingSenderId: '700451722816',
    projectId: 'ascend-eeaae',
    authDomain: 'ascend-eeaae.firebaseapp.com',
    storageBucket: 'ascend-eeaae.firebasestorage.app',
    measurementId: 'G-FNLFPQEDQJ',
  );
}
